### ISSUE TITLE
Problem with reading tweets

### ISSUE THREAD

**Issue by JochenDB** [AronMacDonald/Twitter_Hbase_Impala#1]
Hey,

I altered the code somewhat to delete the HANA logic but I don't think I changed anything that could be causing this. The serializer seems to be having some troubles with retweets? I get these errors in my regionserver logs:

2014-03-08 09:37:44,371 ERROR org.apache.hadoop.hbase.regionserver.HRegionServer: 
org.apache.hadoop.hbase.regionserver.NoSuchColumnFamilyException: Column family retweet does not exist in region tweets,,1394029330397.953f602dd0790637df8106720396f219. in table 'tweets', {NAME => 'entities', DATA_BLOCK_ENCODING => 'NONE', BLOOMFILTER => 'NONE', REPLICATION_SCOPE => '0', COMPRESSION => 'NONE', VERSIONS => '3', TTL => '2147483647', MIN_VERSIONS => '0', KEEP_DELETED_CELLS => 'false', BLOCKSIZE => '65536', ENCODE_ON_DISK => 'true', IN_MEMORY => 'false', BLOCKCACHE => 'true'}, {NAME => 'retweeted_status', DATA_BLOCK_ENCODING => 'NONE', BLOOMFILTER => 'NONE', REPLICATION_SCOPE => '0', COMPRESSION => 'NONE', VERSIONS => '3', TTL => '2147483647', MIN_VERSIONS => '0', KEEP_DELETED_CELLS => 'false', BLOCKSIZE => '65536', ENCODE_ON_DISK => 'true', IN_MEMORY => 'false', BLOCKCACHE => 'true'}, {NAME => 'tweet', DATA_BLOCK_ENCODING => 'NONE', BLOOMFILTER => 'NONE', REPLICATION_SCOPE => '0', COMPRESSION => 'NONE', VERSIONS => '3', TTL => '2147483647', MIN_VERSIONS => '0', KEEP_DELETED_CELLS => 'false', BLOCKSIZE => '65536', ENCODE_ON_DISK => 'true', IN_MEMORY => 'false', BLOCKCACHE => 'true'}, {NAME => 'user', DATA_BLOCK_ENCODING => 'NONE', BLOOMFILTER => 'NONE', REPLICATION_SCOPE => '0', COMPRESSION => 'NONE', VERSIONS => '3', TTL => '2147483647', MIN_VERSIONS => '0', KEEP_DELETED_CELLS => 'false', BLOCKSIZE => '65536', ENCODE_ON_DISK => 'true', IN_MEMORY => 'false', BLOCKCACHE => 'true'}
    at org.apache.hadoop.hbase.regionserver.HRegion.checkFamily(HRegion.java:5475)
    at org.apache.hadoop.hbase.regionserver.HRegion.checkFamilies(HRegion.java:3022)
    at org.apache.hadoop.hbase.regionserver.HRegion.internalPut(HRegion.java:2900)
    at org.apache.hadoop.hbase.regionserver.HRegion.put(HRegion.java:2083)
    at org.apache.hadoop.hbase.regionserver.HRegionServer.put(HRegionServer.java:2239)
    at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.hadoop.hbase.ipc.WritableRpcEngine$Server.call(WritableRpcEngine.java:323)
    at org.apache.hadoop.hbase.ipc.HBaseServer$Handler.run(HBaseServer.java:1428)

More information here: http://stackoverflow.com/questions/22208912/flume-transactions-to-hbase-failing

**Comment by AronMacDonald** [comment]
Hi.

Not sure I hit that. But would suggest you check hbase is working via hbase shell.

You might also need to create the hbase table first.
E.g.

create 'tweets', {NAME => 'tweet'}, {NAME => 'retweeted_status'}, {NAME => 'entities'}, {NAME => 'user'}

Hope that helps
Aron

Sent from Samsung Mobile

-------- Original message --------

**Comment by JochenDB** [comment]
I will try it again on a different VM later today, as my current one is having some other issues lately and I will keep you informed.

**Comment by AronMacDonald** [comment]
Ok no problem. But please be aware that I didn't do it on a vm, so not sure if this will add any complexity accessing the twitter api etc.
Vm's may also can have limited memory as well so that may also cause issues.
Are you using cloudera VM?
I hope you get it working. If you do then please let me know. :-)

Sent from Samsung Mobile

-------- Original message --------

**Comment by JochenDB** [comment]
Hello Aron,

changing the column family name from 'retweeted_status' to 'retweet' as suggested on StackOverflow ( http://stackoverflow.com/questions/22208912/flume-transactions-to-hbase-failing ) fixed the error, maybe you should change this in the readme :) Thanks for helping out!

**Comment by AronMacDonald** [comment]
Thanks for the feedback, I've updated the readme. Sorry for that I should have noticed the typo.
